### ISSUE TITLE
Write to wiki fails on add to Git (intermittent)

### ISSUE THREAD

**Issue by davidsowerby** [davidsowerby/changelog#14]
Is reported as file does not exist, even though it is actually there.  The Git add command is very close to the file write - is this caused by a fractional delay in the OS completing the write, even though this is being written locally?

> Caused by: uk.q3c.build.gitplus.local.GitLocalException: Unable to add file to git: /home/david/git/simplycd-lifecycle.wiki/changelog.md
        at uk.q3c.build.gitplus.local.DefaultGitLocal.add(DefaultGitLocal.kt:229)
        at uk.q3c.build.changelog.DefaultChangeLog.generate(DefaultChangeLog.kt:78)
        at uk.q3c.build.changelog.ChangeLog$generate.call(Unknown Source)
        at uk.q3c.simplycd.lifecycle.GenerateChangeLogTask.generate(GenerateChangeLogTask.groovy:22)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:136)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:129)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:118)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:623)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:606)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 68 more
Caused by: org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
        at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:247)
        at uk.q3c.build.gitplus.local.DefaultGitLocal.add(DefaultGitLocal.kt:227)
        ... 79 more
Caused by: java.io.IOException: No such file or directory
        at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.newTempFile(ObjectDirectoryInserter.java:236)
        at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.toTemp(ObjectDirectoryInserter.java:202)
        at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.insert(ObjectDirectoryInserter.java:93)
        at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.insert(ObjectDirectoryInserter.java:104)
        at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:228)

**Comment by davidsowerby** [comment]
Actually caused by wiki directory not being Git initialised - that needs to b trapped and reported more accurately
